spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_bank
    username: postgres
    password: badiro12
    driver-class-name: org.postgresql.Driver

    pool:
      min-idle: 5
      max-active: 10


